SECTIONS = {
    "V7": [
        "V7: (2, 4, 5 questions together in free form. The ones in color green have to go in tandem, meaning that you cannot have 'why' by itself without the previous question)"
    ],
    "Daily": [
        "What is Great about Your Life Now?",
        "How are You Making Your Life Awesome?",
        "What are You Most Grateful for?",
        "Why do You Feel Grateful?",
        "What are You Most Excited About Your Life Now?",
        "What are You Most Proud of?",
        "Why makes you Feel Proud?",
        "What are You Most Committed to in Your Life Now?",
        "What Will You Not Allow to Continue Happening?",
        "Why?",
        "What Inspires You the Most?",
        "Why?",
        "How Could You 10X Your Life Now?",
        "What are You Going to do to Exponentially Improve Your Life Now?",
        "How Could you Make Your Life 10X More Fun?",
        "What are Your 3-Biggest Dreams for Your Life?",
        "What would the Most Spectacular Vision for Your Life be Like?",
        "How Would Your Ideal Life be Like?",
        "How Would Your ideal Day be Like? Where Would You Live? What would You do?",
        "What Do You Value the Most in Your Life?",
        "What is Your Ultimate Purpose?",
        "What is Your Plan to Fulfill Your Ultimate Purpose?",
        "Remember some Amazing things You Have Done in Your Life:",
        "List 5-Great Accomplishments:",
        "What are You Willing to Promise Yourself?",
        "List Your 3-Most Important Goals For this Week, Your Top Results:",
        "List Your 3-Most Important Goals for this Year:",
        "What is the Most Important Lesson You Have Learn?",
        "What do You Want to be the Best in the World at?",
        "What Do You Want People to say About You when You are Gone?",
        "If You Could Create, do, or Achieve Anything, What Would it be?",
        "What are Your Wildest Dreams?",
        "How Could You Make a much Bigger and Better Contribution to Your Community and the World?",
        "Who do You Love?",
        "Who Loves You the Most?"
    ],
    "Top": [
        "What is Your Ultimate Purpose?",
        "What Exactly do You Want to Achieve or Make Happen?",
        "What are You Most Grateful for in Your Life?",
        "What are You Most Excited About in Your Life Now?",
        "What are You Most Committed to in Your Life Now?",
        "How are You Making Your Life Awesome?",
        "What’s the Highest and Best use of Your time Now?",
        "What’s the Highest and Best use of Your Money Now?",
        "What is Your Intuition telling You?",
        "How Would the Most Spectacular Vision for Your Life be Like?",
        "How Could You Make Your Life 10 times More Fun and Exciting?",
        "What Do You Want People to say About You when You are Gone?",
        "How Could You Make a Much Bigger and Better Contribution to Your Community and the World?"
    ],
    "Now": [
        "What Exactly do You Want Now?",
        "What Exactly Do You Want in this Situation?",
        "Why?",
        "What Actions are You Committed to take to Make it the Way You want it?",
        "What is the Highest and Best use of Your Time Now?",
        "What is the Highest and Best use of Your Money Now?",
        "What Does Your Intuition is Telling You?",
        "How Could You Easily Accelerate Results and Success?",
        "How Can You Make it Easier, Faster and Better?"
    ],
    "Overcome": [
        "What is Great about this Problem or Challenge?",
        "What’s Not perfect yet?",
        "How Exactly Would You Like this Situation to be Like?",
        "What Actions are You Committed to take to make it the way you want it?",
        "How Can You Empower and Support others with the Same Challenges as You Have Now?"
    ],
}
